[build]
  base = "/"
  command = "yarn build:demo"
  publish = "dev-test/"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':!website/'"

  [build.environment]
    YARN_FLAGS = "--frozen-lockfile"
    YARN_VERSION = "1.19.1"
