name: 'Docs Linting:'
on:
  push:
    branches:
      - master

    paths:
      - '.github/workflows/docslint.yml'
      - 'website/**'

  pull_request:
    types: [opened, synchronize, reopened]

    paths:
      - '.github/workflows/docslint.yml'
      - 'website/**'

jobs:
  Prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale Linter
        uses: errata-ai/vale-action@cea2c66ec347c6b516bca064dd980faf350b070c
        with:
          # Optional
          files: website/content/docs
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
